Repository Skatteetaten/terraform-nomad-postgres, pull requests merged in 2020-10, with the labels that each got.

#23 Feature/sync med origin
  .github/action/create-env.py
  .github/linters/.tflint.hcl
  .github/workflows/on_pr_push_master.yml
  .gitignore
  LICENSE
  Makefile
  README.md
  Vagrantfile
  Vagrantfile.default
  dev/ansible/README.md
  dev/vagrant/conf/README.md
  dev/vagrant/conf/consul/README.md
  dev/vagrant/conf/nomad/README.md
  dev/vagrant/conf/pre_bootstrap/README.md
  dev/vagrant/conf/vault/README.md
  docker/README.md
  example/README.md
  example/vagrant_box_example/README.md
  example/vagrant_box_example/main.tf
  example/vagrant_box_example/nomad_acl.tf
  example/variables.tf
  main.tf
  outputs.tf
  template_example/.env
  template_example/Vagrantfile
  template_example/conf/nomad/countdash.hcl
  template_example/dev/ansible/01_build_docker_image.yml
  template_example/dev/ansible/02_run_terraform.yml
  template_example/dev/ansible/playbook.yml
  template_example/dev/vagrant/conf/consul/99-override.hcl
  template_example/dev/vagrant/conf/nomad/99-override.hcl
  template_example/dev/vagrant/conf/post_ansible.sh
  template_example/dev/vagrant/conf/post_bootstrap/00-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/01-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/02-poststart-example.yml
  template_example/dev/vagrant/conf/pre_ansible.sh
  template_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/01-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/02-prestart-example.yml
  template_example/dev/vagrant/conf/vault/99-override.hcl
  template_example/docker/.dockerignore
  template_example/docker/Dockerfile
  template_example/docker/conf/certificates/.gitignore
  template_example/docker/conf/certificates/README.md
  template_example/example/standalone/main.tf
  template_example/example/standalone/nomad_acl.tf
  template_example/example/standalone/variables.tf
  template_example/main.tf
  template_example/outputs.tf
  template_example/variables.tf
  test_example/example/main.tf
  test_example/example/variables.tf
  test_example/outputs.tf
  variables.tf
Labels: documentation, enhancement

#21 added 03_run_test.yml
  CHANGELOG.md
  Makefile
  Vagrantfile
  dev/ansible/00_create_intention.yml
  dev/ansible/03_run_tests.yml
Labels: enhancement

#17 added host volumes
  .gitignore
  CHANGELOG.md
  README.md
  Vagrantfile
  conf/nomad/postgres.hcl
  dev/vagrant/conf/nomad/mount_host_volume.hcl
  dev/vagrant/conf/post_bootstrap/01-update-nomad-write-default-policy.yml
  dev/vagrant/conf/post_bootstrap/host_volume_policy.hcl
  dev/vagrant/conf/pre_bootstrap/00-create_dir_for_persisting_data.yml
  example/main.tf
  main.tf
  variables.tf
Labels: enhancement, prioritized

#26 Issue 25 add tests persistence
  CHANGELOG.md
  dev/.env
  dev/ansible/04_test_persistence.yml
  dev/ansible/db_testfiles/data.sql
  dev/ansible/db_testfiles/testtable.sql
Labels: enhancement

#31 release 0.1.0
  CHANGELOG.md
Labels: minor

#36 Synced with template and updated box version 0.6.0
  .github/action/find-replace.py
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  Makefile
  Vagrantfile.default
  dev/ansible/00_create_intention.yml
  dev/ansible/01_generate_secrets_vault.yml
  dev/ansible/03_run_tests.yml
  dev/ansible/04_test_persistence.yml
  dev/vagrant/bootstrap/README.md
  dev/vagrant/bootstrap/nomad/post/022-update-nomad-write-default-policy.yml
  dev/vagrant/bootstrap/nomad/post/host_volume_policy.hcl
  dev/vagrant/bootstrap/nomad/pre/00-create_dir_for_persisting_data.yml
  dev/vagrant/bootstrap/vault/post/011-install-plugin-vault-secrets-gen.yml
  dev/vagrant/conf/README.md
  dev/vagrant/conf/post_bootstrap/00-install-plugin-vault-secrets-gen.yml
  dev/vagrant/conf/post_bootstrap/README.md
  example/main.tf
  template_example/dev/vagrant/bootstrap/README.md
  template_example/dev/vagrant/bootstrap/consul/post/510-poststart-example.yml
  template_example/dev/vagrant/bootstrap/consul/post/520-poststart-example.yml
  template_example/dev/vagrant/bootstrap/consul/pre/510-prestart-example.yml
  template_example/dev/vagrant/bootstrap/consul/pre/520-prestart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/00-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/01-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/02-poststart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/01-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/02-prestart-example.yml
  template_example/example/standalone/main.tf
  template_example/example/standalone/providers.tf
Labels: type/enhancement

#39 Removed gen/pwd plugin. Using ansible to generate usr/pwd
  CHANGELOG.md
  dev/ansible/01_generate_secrets_vault.yml
  dev/vagrant/bootstrap/vault/post/011-install-plugin-vault-secrets-gen.yml
Labels: type/enhancement

#38 Adding github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: theme/ci

#40 Removed ambiguous code in ansible playbooks
  CHANGELOG.md
  dev/ansible/00_create_intention.yml
  dev/ansible/04_test_persistence.yml
Labels: type/bug

#42 Removed template_example
  CHANGELOG.md
  template_example/.env
  template_example/Vagrantfile
  template_example/conf/nomad/countdash.hcl
  template_example/dev/ansible/01_build_docker_image.yml
  template_example/dev/ansible/02_run_terraform.yml
  template_example/dev/ansible/playbook.yml
  template_example/dev/vagrant/bootstrap/README.md
  template_example/dev/vagrant/bootstrap/consul/post/510-poststart-example.yml
  template_example/dev/vagrant/bootstrap/consul/post/520-poststart-example.yml
  template_example/dev/vagrant/bootstrap/consul/pre/510-prestart-example.yml
  template_example/dev/vagrant/bootstrap/consul/pre/520-prestart-example.yml
  template_example/dev/vagrant/conf/consul/99-override.hcl
  template_example/dev/vagrant/conf/nomad/99-override.hcl
  template_example/dev/vagrant/conf/post_ansible.sh
  template_example/dev/vagrant/conf/pre_ansible.sh
  template_example/dev/vagrant/conf/vault/99-override.hcl
  template_example/docker/.dockerignore
  template_example/docker/Dockerfile
  template_example/docker/conf/certificates/.gitignore
  template_example/docker/conf/certificates/README.md
  template_example/example/standalone/main.tf
  template_example/example/standalone/providers.tf
  template_example/example/standalone/variables.tf
  template_example/main.tf
  template_example/outputs.tf
  template_example/variables.tf
Labels: theme/template

#43 Release 0.2.0
  CHANGELOG.md
  dev/README.md
  dev/ansible/README.md
  dev/vagrant/bootstrap/README.md
  dev/vagrant/conf/README.md
  dev/vagrant/conf/consul/README.md
  dev/vagrant/conf/nomad/README.md
  dev/vagrant/conf/vault/README.md
  docker/README.md
  example/README.md
  example/vagrant_box_example/README.md
Labels: minor
