Repository Skatteetaten/terraform-nomad-postgres, pull requests merged in 2020-11, with the labels that each got.

#47 Added switch, intentions section, proper rendering of credentials ++
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/postgres.hcl
  dev/ansible/02_run_terraform.yml
  dev/ansible/04_test_persistence.yml
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  dev/vagrant/conf/nomad/00-enable_vault.hcl
  example/README.md
  example/main.tf
  example/postgres_standalone/README.md
  example/postgres_standalone/main.tf
  example/postgres_standalone/providers.tf
  example/postgres_standalone/variables.tf
  example/vagrant_box_example/README.md
  example/vagrant_box_example/main.tf
  example/vagrant_box_example/nomad_acl.tf
  main.tf
  outputs.tf
  variables.tf
Labels: type/documentation, type/enhancement

#50 HOTFIX: Setting default values to true
  README.md
  variables.tf
Labels: skip-changelog, skip-linter, type/bug

#53 Resources to variables & updated box version
  CHANGELOG.md
  Makefile
  README.md
  Vagrantfile.default
  conf/nomad/postgres.hcl
  dev/ansible/04_test_persistence.yml
  dev/vagrant/bootstrap/nomad/post/022-update-nomad-write-default-policy.yml
  example/postgres_standalone/providers.tf
  main.tf
  variables.tf
Labels: type/documentation, type/enhancement

#54 Release 0.3.0
  CHANGELOG.md
Labels: minor

#55 Hotfix: Removed "bug" in Vault policy & upated readme
  CHANGELOG.md
  Makefile
  README.md
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
Labels: type/bug, type/documentation

#57 Expand sidecar_service postgres resources
  CHANGELOG.md
  README.md
  conf/nomad/postgres.hcl
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  main.tf
  variables.tf
Labels: type/enhancement

#62 Updated variables
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/postgres.hcl
  example/postgres_standalone/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#63 Release 0.4.0
  CHANGELOG.md
Labels: minor
